export const COMPANY_ADMIN_ROLE = "company_admin";

export const PERMISSIONS = [
  ["company.view", "company", "view", "View company profile and settings"],
  ["company.update", "company", "update", "Update company profile and settings"],
  ["numbering.view", "numbering", "view", "View document numbering"],
  ["numbering.update", "numbering", "update", "Update document numbering"],
  ["accounting_profile.view", "accounting_profile", "view", "View the country accounting profile"],
  ["accounting_profile.update", "accounting_profile", "update", "Update the country accounting profile"],
  ["tax_codes.view", "tax_codes", "view", "View tax codes"],
  ["tax_codes.manage", "tax_codes", "manage", "Create and retire tax codes"],
  ["users.view", "users", "view", "View users"],
  ["users.create", "users", "create", "Create users"],
  ["users.update", "users", "update", "Update users and active status"],
  ["roles.view", "roles", "view", "View roles and the permission catalog"],
  ["roles.create", "roles", "create", "Create roles"],
  ["roles.update", "roles", "update", "Update roles and their permissions"],
  ["branches.view", "branches", "view", "View branches and locations"],
  ["branches.create", "branches", "create", "Create branches and locations"],
  ["branches.update", "branches", "update", "Update branches and locations"],
  ["accounts.view", "accounts", "view", "View the chart of accounts"],
  ["accounts.create", "accounts", "create", "Create accounts"],
  ["accounts.update", "accounts", "update", "Update or delete accounts"],
  ["periods.view", "periods", "view", "View fiscal years and periods"],
  ["periods.manage", "periods", "manage", "Create fiscal years and periods"],
  ["periods.close", "periods", "close", "Close fiscal years and periods"],
  ["periods.reopen", "periods", "reopen", "Reopen fiscal years and periods"],
  ["journals.view", "journals", "view", "View journal entries"],
  ["journals.create", "journals", "create", "Create draft journal entries"],
  ["journals.update", "journals", "update", "Edit draft journal entries"],
  ["journals.submit", "journals", "submit", "Submit journal entries for approval"],
  ["journals.approve", "journals", "approve", "Approve or reject journal entries"],
  ["journals.post", "journals", "post", "Post approved journal entries"],
  ["journals.reverse", "journals", "reverse", "Reverse posted journal entries"],
  ["journals.void", "journals", "void", "Void unposted journal entries"],
  ["reports.view", "reports", "view", "View official financial reports"],
  ["reports.export", "reports", "export", "Export official financial reports"],
  ["audit.view", "audit", "view", "View the audit log"],
  ["customers.view", "customers", "view", "View customers, balances, and statements"],
  ["customers.create", "customers", "create", "Create customers"],
  ["customers.update", "customers", "update", "Update customers and opening detail"],
  ["products.view", "products", "view", "View products and services"],
  ["products.create", "products", "create", "Create products, categories, and units"],
  ["products.update", "products", "update", "Update products, categories, and units"],
  ["invoices.view", "invoices", "view", "View sales invoices"],
  ["invoices.create", "invoices", "create", "Create sales invoices"],
  ["invoices.update", "invoices", "update", "Edit draft sales invoices"],
  ["invoices.submit", "invoices", "submit", "Submit sales invoices"],
  ["invoices.approve", "invoices", "approve", "Approve or reject sales invoices"],
  ["invoices.post", "invoices", "post", "Post sales invoices"],
  ["invoices.void", "invoices", "void", "Void unposted sales invoices"],
  ["invoices.reverse", "invoices", "reverse", "Reverse posted sales invoices"],
  ["invoices.override_due_date", "invoices", "override_due_date", "Set an invoice due date that differs from the payment terms"],
  ["invoices.override_credit_limit", "invoices", "override_credit_limit", "Post an invoice that exceeds the customer credit limit"],
  ["receipts.view", "receipts", "view", "View customer receipts"],
  ["receipts.create", "receipts", "create", "Create customer receipts"],
  ["receipts.update", "receipts", "update", "Edit draft customer receipts"],
  ["receipts.submit", "receipts", "submit", "Submit customer receipts"],
  ["receipts.approve", "receipts", "approve", "Approve or reject customer receipts"],
  ["receipts.post", "receipts", "post", "Post customer receipts"],
  ["receipts.allocate", "receipts", "allocate", "Allocate or unallocate a posted receipt"],
  ["receipts.void", "receipts", "void", "Void unposted customer receipts"],
  ["receipts.reverse", "receipts", "reverse", "Reverse posted customer receipts"],
  ["customer_returns.view", "customer_returns", "view", "View customer returns"],
  ["customer_returns.create", "customer_returns", "create", "Create customer returns linked to an invoice line"],
  ["customer_returns.create_unreferenced", "customer_returns", "create_unreferenced", "Create a customer return that has no source invoice"],
  ["customer_returns.update", "customer_returns", "update", "Edit draft customer returns"],
  ["customer_returns.submit", "customer_returns", "submit", "Submit customer returns"],
  ["customer_returns.approve", "customer_returns", "approve", "Approve or reject customer returns"],
  ["customer_returns.post", "customer_returns", "post", "Post customer returns"],
  ["customer_returns.void", "customer_returns", "void", "Void unposted customer returns"],
  ["customer_returns.reverse", "customer_returns", "reverse", "Reverse posted customer returns"],
] as const;

export type PermissionCode = (typeof PERMISSIONS)[number][0];

export const PERMISSION_CODES = new Set<string>(PERMISSIONS.map((item) => item[0]));
